config/routes.rb
Rails.application.routes.draw do

  # devise_for :users
  devise_for :users, :controllers => { :registrations => "registrations" }
  resource :user

  root to: 'static#index'

  get 'static/about'
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :age, numericality: { greater_than_or_equal_to: 0 }

  def experience
    self.work_experience
  end
  
  def experience=(experience_params)
    self.work_experience = markdown(experience_params)
  end

  def user_skill
    self.skill
  end

  def user_skill=(skill_params)
    self.skill = markdown(skill_params)
  end

  def markdown(text)
    markdown_render = Redcarpet::Render::HTML.new(hard_wrap: true, no_styles: true)
    markdown = Redcarpet::Markdown.new(markdown_render, autolink: true, no_intro_emphasis: true) 
    markdown.render(text).html_safe
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout :layout_by_resource

  private

  def layout_by_resource
    if devise_controller?
      'for_devise'
    else
      'application'
    end
  end

  def after_sign_in_path_for(resource)
    user_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def after_sign_up_path_for(resource)
    user_path
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'user'

  def show    
  end

  def edit    
  end

  def update 
    if current_user.update(update_params)
      redirect_to user_path
    else
      render 'edit'
    end
  end

  private

  def update_params
    params.require(:user).permit(:name, :age, :city, :github, :skill, :experience)
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title This!
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

  body
    .container
      .row 
        .col-md-12
          = render 'layouts/shared/nav'
          = render "layouts/shared/head"
          .container
            .row
            = yield

app/views/layouts/for_devise.html.slim
doctype html
html
  head
    title This!
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

  body
    .container
      .row.content
        = yield

app/views/layouts/head/_head.html.slim
head.inner id="head"
  h1.animated.bounceInDown
    #headerbg aaaaaaaaaaa
  .container
    .row
      .col-md-8.col-md-offset-2
        ul.nav.nav-tabs role="tablist"
          li role="presentation" class="active"
            = link_to "Home", "#"
          li role="presentation"
            = link_to "Archives", "#"
          li role="presentation"
            = link_to "About Me", "#"

          li
            = link_to "sign up", new_user_registration_path

app/views/layouts/shared/_head.html.slim
head.inner id="head"
  h1.animated.bounceInDown
    #headerbg aaaaaaaaaaa
  .container
    .row
      .col-md-8.col-md-offset-2
        ul.nav.nav-tabs role="tablist"
          li role="presentation" class="#{ 'active' if params[:controller] == 'static' && params[:action] == 'index' }"
            = link_to "Home", root_path
          li role="presentation"
            = link_to "Archives", "#"
          li role="presentation" class="#{ 'active' if params[:controller] == 'static' && params[:action] == 'about' }"
            = link_to "About Me",  static_about_path

app/views/layouts/shared/_nav.html.slim
ul.nav.navbar-nav.navbar-right
  li.dropdown
    a.dropdown-toggle data-toggle="dropdown" href="#" 
      | Dropdown
      span.caret
    ul.dropdown-menu role="menu" 
      - if signed_in?
        li role="presentation" 
          = link_to "sign out",  destroy_user_session_path, method: :delete
        li role="presentation" 
          = link_to "me", user_path
      - else
        li role="presentation" 
          = link_to "sign in", new_user_session_path

app/views/layouts/shared/_user_head.html.slim
= render 'layouts/shared/nav'
head.inner id="head"
  h1.animated.bounceInDown
    #headerbg do it
  .container
    .row
      .col-md-8.col-md-offset-2
        ul.nav.nav-tabs role="tablist"
          li role="presentation" class="#{ 'active' if params[:controller] == 'static' }"
            = link_to "Home", root_path
          li role="presentation"
            = link_to "Archives", "#"
          li role="presentation" class="#{ 'active' if params[:controller] == 'users' && params[:action] == 'show'}"
            = link_to "me", user_path

app/views/layouts/user.html.slim
doctype html
html
  head
    title This!
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

  body
    .container
      .row
          header
            = yield :pagetitle

          .container  
            .row.content
              = yield

app/views/users/edit.html.slim
.col-md-8.col-md-offset-2
  br
  = simple_form_for(current_user, url: user_path, method: :patch) do |f|
    = f.input :name
    = f.input :age
    = f.input :city
    = f.input :github
    = f.input :user_skill, input_html: { class: 'rich_text_format' }
    = f.input :experience, as: :text, input_html: { id: 'editor' }
    = f.button :submit, class: 'btn, btn-default'

app/views/users/show.html.slim
.col-md-8.col-md-offset-2
  br
  .table-responsive
    table.table
      colgroup
        tbody
          tr.info
            td.col-md-2.text-right
              code name
            td.col-md-6 #{current_user.name}
          tr.info
            td.text-right
              code email
            td #{current_user.email}
          tr.info
            td.text-right
              code age
            td #{current_user.age}
          tr.info
            td.text-right
              code city
            td #{current_user.city}
          tr.info
            td.text-right
              code github
            td #{current_user.github}
          tr.info
            td.text-right
              code current_sign_in_ip
            td #{current_user.current_sign_in_ip}
          tr.info
            td.text-right
              code last_sign_in_ip
            td #{current_user.last_sign_in_ip}
          tr.info
            td.text-right
              code skill
            td #{sanitize current_user.skill}
          tr.info
            td.text-right
              code work_experience
            td #{sanitize current_user.work_experience}

  = link_to "edit", edit_user_path, class: "btn btn-default"